# Generated by Django 3.2.9 on 2022-03-10 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, verbose_name='タイトル')),
                ('description', markdownx.models.MarkdownxField()),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='編集日')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('is_public', models.BooleanField(default=False, verbose_name='公開する')),
                ('comment', models.ManyToManyField(blank=True, to='common.Comment', verbose_name='コメント')),
                ('good', models.ManyToManyField(blank=True, related_name='article', to='common.Good', verbose_name='グッド')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article', to='common.language')),
                ('tag', models.ManyToManyField(blank=True, to='common.Tag', verbose_name='タグ')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
    ]
