# Generated by Django 3.2.9 on 2022-03-05 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='タイトル')),
                ('description', markdownx.models.MarkdownxField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ManyToManyField(blank=True, to='common.Comment', verbose_name='コメント')),
                ('good', models.ManyToManyField(blank=True, related_name='question', to='common.Good', verbose_name='グッド')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question', to='common.language')),
                ('tag', models.ManyToManyField(blank=True, to='common.Tag', verbose_name='タグ')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
